### ISSUE TITLE
You saw shunit2?

### ISSUE THREAD

**Issue by rugk** [Neilpang/acmetest#2]
Seems you implemented your own test framework/runner. You noticed https://github.com/kward/shunit2 by @kward exists, which provides all the basic things already? 😶

Don't know whether a switch is worth it, just wanted to make you aware of it.

**Comment by Neilpang** [comment]
Sorry, I don't like it.
it's `bash` script, but acme.sh is `sh` compatible.

**Comment by rugk** [comment]
No, it's `/bin/sh`.
